src/domain/exceptions/exceptions.interface.ts, src/domain/model/comment.ts, src/domain/model/video.ts, src/domain/repositories/video.repository.ts, src/infrastructure/entities/comment.entity.ts, src/infrastructure/entities/video.entity.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/video/video.controller.ts, src/usecase/video/video-adoption.ts
=> 33 video adoption api

src/domain/exceptions/exceptions.interface.ts, src/domain/repositories/comment.repository.ts, src/infrastructure/controllers/controllers.module.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/comment.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/comment/comment.controller.ts, src/usecase/comment/comment-adoption.ts
댓글 채택 API입니다.
확인해주시고 리뷰 달아주세요.
=> 34 comment adoption api

src/domain/exceptions/exceptions.interface.ts, src/domain/repositories/like.repository.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/like.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/like/like.controller.ts, src/usecase/like/create-like.ts, src/usecase/like/delete-like.ts
=> 17 delete like api

src/domain/exceptions/exceptions.interface.ts, src/domain/repositories/video.repository.ts, src/infrastructure/entities/comment.entity.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/comment/comment.controller.ts, src/presentation/video/video.controller.ts, src/usecase/comment/comment-adoption.ts, src/usecase/like/delete-like.ts, src/usecase/video/create-video-comment.ts
영상 답변 생성 API 로직 추가했습니다.
확인해주세요.
=> 9 comment api

src/domain/exceptions/exceptions.interface.ts, src/domain/repositories/dto/user.dto.ts, src/domain/repositories/user.repository.ts, src/infrastructure/controllers/controllers.module.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/user.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/user/user.controller.ts, src/presentation/user/user.presenter.ts, src/usecase/user/user-info.ts
프로필 들어갔을 시 나오는 유저 정보 조회 API 입니다.
확인해주세요
=> 39 user info api

src/domain/exceptions/exceptions.interface.ts, src/domain/repositories/dto/user.dto.ts, src/domain/repositories/user.repository.ts, src/domain/repositories/video.repository.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/user.repository.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/user/user.controller.ts, src/presentation/user/user.presenter.ts, src/usecase/user/user-question-video.ts
프로필 영상 리스트 조회 API 입니다.
빠트린 부분 있는지 확인해주세요
감사합니다.
=> 41 user video api

src/domain/repositories/comment.repository.ts, src/infrastructure/entities/comment.entity.ts, src/infrastructure/entities/user.entity.ts, src/infrastructure/repositories/comment.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/video/video.controller.ts, src/usecase/video/delte-answer-comment.ts
글 답변 삭제 api 입니다.
빠트린 부분 있는지 확인해주세요
=> 18 delete comment api

package-lock.json, package.json, src/infrastructure/config/typeorm/typeorm.module.ts
=> 43 TypeORM에서 Camelcase 필드를 Snake 컬럼에 매핑하기

src/domain/interfaces/payload.interface.ts, src/domain/repositories/video.repository.ts, src/infrastructure/entities/comment.entity.ts, src/infrastructure/entities/video.entity.ts, src/infrastructure/repositories/comment.repository.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/answer/answer.controller.ts, src/presentation/comment/comment.controller.ts, src/presentation/like/like.controller.ts, src/presentation/question/question.controller.ts, src/presentation/video/video.controller.ts, src/usecase/question/delete-question.ts
질문 삭제 API입니다.
잘못된 부분 있는지 확인 부탁드립니다.
=> 49 delete question api

src/infrastructure/repositories/comment.repository.ts, src/infrastructure/repositories/user.repository.ts, src/infrastructure/repositories/video.repository.ts
=> 51 delete flag filtering

src/domain/model/comment.ts, src/domain/model/video.ts, src/domain/repositories/comment.repository.ts, src/domain/repositories/video.repository.ts, src/infrastructure/repositories/comment.repository.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/answer/answer.controller.ts, src/usecase/answer/create-comment-answer.ts, src/usecase/answer/create-video-answer.ts
=> 11 create comment answer api

src/domain/model/user.ts, src/infrastructure/entities/user.entity.ts
=> ⚡️ :: (#58) add column createdAt, updatedAt

package-lock.json, package.json, src/domain/config/es.interface.ts, src/infrastructure/config/elasticsearch/elasticsearch.module.ts, src/infrastructure/config/elasticsearch/elasticsearch.service.ts, src/infrastructure/config/environment-config/environment-config.service.ts, src/infrastructure/controllers/controllers.module.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/search/search.controller.ts, src/usecase/search/get-autocomplete.ts
자동 완성 API 입니다.
ES_NODE_ENDPOINT
ES_USERNAME
ES_PASSWORD
환경 변수 추가 되었습니다.
elasticsearch client singleton으로 만들어 봤습니다 확인 부탁드립니당
=> #59 자동완성 API

src/domain/repositories/video.repository.ts, src/infrastructure/repositories/video.repository.ts, src/presentation/answer/answer.controller.ts, src/presentation/question/question.controller.ts, src/usecase/answer/get-video-answer-list.ts, src/usecase/question/get-questions-list.ts
Close #64 
영상 답변 리스트, 질문 리스트 무한스크롤 적용 했습니다.
확인부탁드립니다.
=> #64 implement infinite scroll

src/domain/repositories/video.repository.ts
=> :recycle: :: (#71) 경로 변경

src/domain/model/user.ts, src/domain/model/video.ts
=> :bug: :: (#81) @Transform null 반환 버그 해결

src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/search/search.controller.ts, src/usecase/search/query-autocomplete.ts, src/usecase/search/query-hash-tag.ts, src/usecase/search/query-title.ts
=> 🔀 :: (#83) 검색 Api

src/usecase/search/query-title.ts
=> 🔀 :: (#85) Title 검색 반환값

src/usecase/search/query-autocomplete.ts
=> 🔀 :: (#89) 잘못된 index 명

src/infrastructure/usecases-proxy/usecases-proxy.module.ts
=> 🐛 :: (#95) fix CD error

src/domain/repositories/video.repository.ts, src/infrastructure/repositories/video.repository.ts, src/presentation/user/user.controller.ts, src/usecase/user/user-question-video.ts
유저 질문 목록 조회 api response 추가 했고 무한 스크롤 적용했습니다.
확인해주세요
=> 97 user question list bug

src/domain/model/comment.ts, src/domain/model/video.ts, src/domain/repositories/comment.repository.ts, src/domain/repositories/video.repository.ts, src/infrastructure/repositories/comment.repository.ts, src/infrastructure/repositories/video.repository.ts, src/presentation/answer/answer.controller.ts, src/presentation/like/like.controller.ts, src/presentation/question/question.controller.ts, src/presentation/user/user.controller.ts, src/presentation/video/video.controller.ts, src/usecase/answer/get-video-answer-list.ts, src/usecase/comment/get-text-answer.ts, src/usecase/question/get-questions-list.ts
=> 100 is_mine check response

src/domain/repositories/video.repository.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/question/question.controller.ts, src/usecase/question/get-question-detail.ts
=> 102 find question detail API

src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/answer/answer.controller.ts, src/presentation/question/question.controller.ts, src/usecase/answer/create-text-answer.ts, src/usecase/answer/delte-text-answer.ts, src/usecase/answer/get-text-answer.ts, src/usecase/answer/get-video-answer-list.ts, src/usecase/question/get-question-hashtag-list.ts, src/usecase/question/get-questions-list.ts
usecase 이름 맞췄습니다.
확인해주세요.
파일 이름도 변경했으니 확인바랍니다.
=> 104 usecase convention

src/domain/exceptions/exceptions.interface.ts, src/domain/model/iq.ts, src/domain/repositories/hash-tag.repository.ts, src/domain/repositories/iq.repository.ts, src/domain/repositories/video.repository.ts, src/infrastructure/entities/video.entity.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/hash-tag.repository.ts, src/infrastructure/repositories/iq.repository.ts, src/infrastructure/repositories/repositories.module.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/question/question.controller.ts, src/presentation/question/question.dto.ts, src/usecase/question/create-question.ts, src/usecase/question/get-question-hashtag-list.ts, src/usecase/video/video-adoption.ts
확인 열심히 하고 pr 날렸지만 혹시 모르니 빠뜨린 로직이나, exception 처리가 빠진 부분이 있는지 확인해주세요.
=> 130 compensation logic

src/domain/model/action_point.ts, src/domain/model/action_point_category.ts, src/infrastructure/entities/action_point.entity.ts, src/infrastructure/entities/action_point_category.entity.ts, src/infrastructure/entities/user.entity.ts
=> 132 db add action point table

src/infrastructure/repositories/video.repository.ts
=> ⚡️ :: (#137) order by random

src/domain/exceptions/exceptions.interface.ts, src/domain/model/tier.ts, src/domain/repositories/tier.repository.ts, src/infrastructure/controllers/controllers.module.ts, src/infrastructure/entities/tier.entity.ts, src/infrastructure/entities/user.entity.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/repositories.module.ts, src/infrastructure/repositories/tier.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/wallet/wallet.controller.ts, src/usecase/wallet/wallet-info.ts
=> 122 get wallet info api

src/domain/model/block.ts, src/domain/repositories/block.repository.ts, src/domain/repositories/video.repository.ts, src/infrastructure/entities/block.entity.ts, src/infrastructure/entities/user.entity.ts, src/infrastructure/repositories/block.repository.ts, src/infrastructure/repositories/repositories.module.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/user/user.controller.ts, src/usecase/user/user-block.ts
=> 143 block API

src/domain/exceptions/exceptions.interface.ts, src/domain/repositories/action-point.repository.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/action-point.repository.ts, src/infrastructure/repositories/repositories.module.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/wallet/action-point.dto.ts, src/presentation/wallet/action-point.presenter.ts, src/presentation/wallet/wallet.controller.ts, src/usecase/wallet/action-point.ts
=> 145 오늘의 행동점수 계산 API

src/domain/exceptions/exceptions.interface.ts, src/domain/model/iq-payment-category.ts, src/domain/model/iq-payment-history.ts, src/domain/repositories/iq-payment-history.ts, src/infrastructure/entities/iq-payment-category.entity.ts, src/infrastructure/entities/iq-payment-history.entity.ts, src/infrastructure/entities/user.entity.ts, src/infrastructure/exceptions/exceptions.service.ts, src/infrastructure/repositories/iq-payment-history.repository.ts, src/infrastructure/repositories/repositories.module.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/wallet/payment-history.presenter.ts, src/presentation/wallet/wallet.controller.ts, src/usecase/wallet/payment-history.ts
=> 148 IQ 지급 내역 가져오기 API

src/domain/model/user.ts, src/domain/repositories/user.repository.ts, src/infrastructure/entities/user.entity.ts, src/infrastructure/repositories/user.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/user/user.controller.ts, src/usecase/user/upsert-expo-token.ts
=> 154 update expo token api

src/domain/model/user.ts, src/infrastructure/entities/follow.entity.ts, src/infrastructure/entities/user.entity.ts, src/infrastructure/repositories/user.repository.ts
=> 158 get user info add response columns

src/domain/model/video.ts, src/domain/repositories/video.repository.ts, src/infrastructure/entities/video.entity.ts, src/infrastructure/repositories/video.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/video/video.controller.ts, src/usecase/video/video-views.ts
=> 156 views api

src/domain/model/cash-exchange.ts, src/domain/repositories/cash-exchange.repository.ts, src/infrastructure/entities/cash_exchange.entity.ts, src/infrastructure/entities/user.entity.ts, src/infrastructure/repositories/cash_exchange.repository.ts, src/infrastructure/repositories/repositories.module.ts, src/infrastructure/repositories/user.repository.ts, src/infrastructure/usecases-proxy/usecases-proxy.module.ts, src/presentation/user/user.controller.ts, src/presentation/user/user.dto.ts, src/presentation/video/video.controller.ts, src/usecase/user/user-cash-exchange.ts
=> 160 cash exchange api

package.json, test/mock/repositories/types.ts, test/mock/repositories/video.repository.mock.ts, test/usecase/question/get-questions-list.spec.ts
https://github.com/Allie-Knowing/Jaximus/issues/165
Closes #165
=> 165 Get Question List Test
